---
#Define Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---

#Define Jenkins Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: devops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkinsprod
          imagePullPolicy: Never
          env:
            - name: JENKINS_ADMIN_ID
              value: admin
            - name: JENKINS_ADMIN_PASSWORD
              value: admin
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
      #     volumeMounts:
      #       - name: jenkins-home
      #         mountPath: /var/jenkins_home
      # volumes:
      #   - name: jenkins-home
      #     hostPath:
      #       # directory location on host
      #       path: /data
      #       # this field is optional
      #       type: DirectoryOrCreate

---

#Define Service 
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins